[via_verifier]
# Interval between polling db for verification requests (in ms).
poll_interval = 10000
# Coordinator server port.
coordinator_port = 6060
# Coordinator server url.
coordinator_http_url = "http://0.0.0.0:6060"
# Verifier Request Timeout (in seconds)
verifier_request_timeout = 10
# The verifier_mode can be simple verifier or coordinator.
role = "Coordinator"
# The session timeout (seconds).
session_timeout = 30
# The transaction weight limit
max_tx_weight = 380000
# The bridge address merkle root.
bridge_address_merkle_root = ""
